### ISSUE TITLE
Co-occurence of genes as a requirement for testing disassociation

### ISSUE THREAD

**Issue by milnus** [fwhelan/coinfinder#54] opened 2022-04-20 22:11 UTC
Hello!
I am running some disassociation analyses using CoinFinder.
I came across two sets of genes that do not co-occur in any of my genomes (n=2083). They are themselves present in ~900 and ~1100 genomes, so more than enough to not be caught in filters.
In my initial run of the entire dataset I did not see the two sets of genes as being disassociated, which I found odd.

I then made two small examples with genes that do not co-occur, and one where there co-occurrence in one genome.
 Coinfinder tests for disassociation in the example with a single co-occurrence. However, no test is carried out in the no co-occurrence example.

Is this an intended behaviour of CoinFinder?

Example files:
[Coinfinder_test_w_no_overlap.csv](https://github.com/fwhelan/coinfinder/files/8525765/Coinfinder_test_w_no_overlap.csv)
[Coinfinder_test_w_overlap.csv](https://github.com/fwhelan/coinfinder/files/8525766/Coinfinder_test_w_overlap.csv)
[Coinfinder_test_tree.nwk.txt](https://github.com/fwhelan/coinfinder/files/8525769/Coinfinder_test_tree.nwk.txt)

**Comment by fwhelan** [comment] 2022-05-15 10:06
Hi milnus,
So very sorry for not getting back to you sooner. Thank you so much for bringing this to my attention; this is definitely not the intended behaviour of coinfinder. I really appreciate you putting together these example datasets- it was really easy to find and fix this bug because I could play around with your examples so easily!

This is fixed now and committed as v1.2.0, and I've started the process of updating the version on bioconda as well (this might take a few days).

Thanks for finding this and letting me know!!

**Comment by fwhelan** [comment] 2022-05-20 07:36
Hi milnus,
Just to let you know that the new version with this bug fix (v1.2.0) just went live on bioconda about 11 hours ago. I'd be really curious to hear how it works out for you.

**Comment by milnus** [comment] 2022-05-21 23:39
Hi Fiona,
Just took v1.2.0 for a spin and it look great!
It identified a couple of additional pan-clusters that do not overlap in any genome, which is great!!
Thanks for maintaining Coinfinder! It is a great addition to the pan-genome toolkit!

**Comment by fwhelan** [comment] 2022-05-22 16:13
Ah, that's great news! Thanks for confirming, and apologies for the bug in the first place!

**Closed as completed by fwhelan** 2022-05-22 16:13 UTC
